### ISSUE TITLE
Integrate all submodules via postBuild to Python and R path

### ISSUE THREAD

**Issue by georges-schutz** [OpenSenseAction/OPENSENSE_sandbox#30]
Sub-modules are not installed, they are only a code-clone of another repository into the sandbox project.
In order to make this usable in notebooks, there is a need to add the path to each of the sub-module in an automatic way to the project.
This may be realized by using the postBuild process.

**Comment by cchwala** [comment]
From the [mybinder docs](https://mybinder.readthedocs.io/en/latest/using/using.html#share-computational-work-or-papers) I would say that it is better to use the `start` file that is run just before the user sessions starts. The `postBuild` is ran when the container is built, which, in our case, is now done from the separate env repository, where we actually do not yet have the submodules available. Hence, my hope would be to run the `start` script from our code repo directly when a new binder instance is launched.

**Comment by overeem11** [comment]
For RAINLINK to run:
- You need to switch to working directory “RAINLINK” (getwd("RAINLINK") in R shell).
-  Make a subdirectory “Figures”.
- Install RAINLINK via command in R shell: install.packages("RAINLINK_1.3.tar.gz", repos=NULL,type="source")

**Comment by overeem11** [comment]
R CMD INSTALL RAINLINK_1.3.tar.gz

**Comment by overeem11** [comment]
Note that RAINLINK has been successfully tested using R, but R libraries from the Config.R file cannot (all) be loaded properly when using RStudio.

**Comment by cchwala** [comment]
Things did not work out as planed at the beginning of this issue. Submodules are not initialized via the solution provided by #38.
