### ISSUE TITLE
Add concise but complete uses case for CML data processing with OpenMRG data

### ISSUE THREAD

**Issue by cchwala** [OpenSenseAction/OPENSENSE_sandbox#49]
The most prominent item in the sandbox should be a simple showcase for how to do the complete CML processing chain from raw data to interpolated rainfall maps. This can be done with the current code and data in the sandbox. The current notebooks are, however, not complete and/or too detailed. It also takes too much time to download the full OpenMRG dataset which makes the user experience worse.

I suggest to:
- [ ] extract a small subset of the OpenMRG dataset and save it (if file size is small enough) directly in the sandbox
- [ ] reduce one of the existing notebooks and do a very simple CML processing with rainfall maps as end result
- [ ] update the index notebook and put a link to the new use case on the top as the most prominent item

I think this can be done in one PR. If things get complicated along the way we can create new issues, e.g. form the three listed items above, and solve them separately.

**Comment by cchwala** [comment]
My suggestion for new structure in the [index notebook](https://github.com/OpenSenseAction/OPENSENSE_sandbox/blob/5a9ac6e6239c9713bbf66cf25620a432d5dde0dd/notebooks/index.ipynb). Not all parts have to be done now, but I add them here to show the reasoning behind this structure providing the long-term (maybe till October 2023) goal of the sandbox.

---------------------------------------

# Content of the OPENSENSE software sandbox

## Use case with complete workflow
* Simple OpenMRG CML data processing from raw data to rainfall maps
* Example for method intercomparison based on OpenMRG CML data (not critical now)

## Basic example of CML data processing software packages
* Basic example of using pycomlink
* Basic example of using PyNNcml

## Basic example of PWS data processing software packages
* Processing PWS data with PWSQC
* Processing PWS data with pws-pyqc

## Basic example for data merging
* to be discussed... and to be done...

**Comment by maxmargraf** [comment]
Started PR #56. Comments on the notebook are welcome. One issue of the openMRG data with the simple rolling std method for rain event detection are very short CMLs producing very high rain rates. Therefore choosing a "nice" day is not easy.

**Comment by cchwala** [comment]
Closed via #56
