### ISSUE TITLE
add into README workaround for installing jupyter-lab

### ISSUE THREAD

**Issue by fenclmar** [OpenSenseAction/OPENSENSE_sandbox#57]
I would add to readme also instalation of jupyterlab with mamba:
`mamba install -c conda-forge jupyterlab`

It solved my problem with installing jupyterLab using `conda install jupyter-lab`, where I encounttred following issue (WIndows 11 Pro, Version 10.0.22621 Build 22621, System Type	x64-based PC):

```
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:
  - jupyter-lab
Current channels:
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
```

**Comment by cchwala** [comment]
Yes. It is indeed better to use `mamba` and it can not hurt to specify that `conda-forge` has to be used. But it should actually be the priority channel based on our `environment.yml` file.
